### ISSUE TITLE
Services and calculations missing from Azure Estimations

### ISSUE THREAD

**Issue by 4upz** [cloud-carbon-footprint/cloud-carbon-footprint#1021]
## Context
A comparison was made that when requesting estimates using the CLI (and quite possibly through the API as well), some Azure services that you would get in the `subscriptions-chunks` spike branch seem to be left out in our trunk branch. For example, some of the missing services when requesting our own estimates and comparing the two are the following:
```
Event Hubs 
Redis Cache metric tons CO2e Emissions
Azure Database for PostgreSQL 
Azure DNS
Azure Cosmos DB 
Azure Bastion 
Load Balancer
Azure Cognitive Search
Azure DevOps 
Log Analytics 
Functions 
Azure Synapse Analytics 
Logic Apps 
Azure Kubernetes Service
API Management 
Virtual Machine Licenses
Container Instances 
SQL Database 
Azure Databricks 
Azure Data Factory v2 
Azure Database for MySQL 
Advanced Threat Protection 
App Configuration 
Azure Purview 
Security Center 
Network Watcher 
Azure Firewall
Event Grid 
Azure Container Apps 
VPN Gateway 
Cognitive Services 
```

These are most likely being caused due to rate limit retries in the current branch unintentionally skipping over services.

In addition, some services that do show are yielding `NaN` results in the CLI. This is most likely due to very small estimates, but should be investigated as well.

### Related Issue
- #906 

## Tasks
- [ ] Discover the cause of the services missing from the trunk branch
- [ ] Implement a fix that would allow for services to show up in Azure results
- [ ] Investigate and implement a fix for `NaN` values showing in CLI results

### Out of Scope
- Changing behavior of rate limit retries (beyond what is required to include services)

## Tech Tasks
- [ ] Add appropriate test coverage, including edge cases.
- [ ] Run Changesets, bump any packages that have been updated/changed
- [ ] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.
- [ ] If any create-app templates have been updated, make sure to run the [test-create-app script](https://docs.google.com/document/d/1Ei6Cb2DjwEJUNtpULJSxbOuIdAfCARERgE3BSsKWrsc/edit) to ensure it still works properly.

**Comment by 4upz** [comment]
The missing services actually stemmed from a bug in the `subscription-chunks` branch that was causing for the last 30 days to _always_ be_queried in addition to the provided date range. This was getting more estimates/timestamps than intended, and as such, was including services that may not have had usage in the original date range provided (as CCF excludes these from estimate results since they do not show up in the billing data). This is probably why services seemed to be "missing" when comparing the two branches, as the older branch was actually providing more data than was requested.

I will keep an eye out for weird behavior, but I think it's safe to conclude that no services are being skipped as I was able to modify the date range within `trunk` to get multiple sets of results that overall included the services listed. I will continue to look into the `NaN` values

**Comment by 4upz** [comment]
Confirming that some services -- mostly Azure Storage services, are returning null in co2e and kwh for both the CLI and the API.

**Comment by 4upz** [comment]
NaN values are coming from some storage services with usage types such as `P4 LRS Disk` returning undefined when attempting to parse the matching `SSD_MANAGED_DISKS_STORAGE_GB` constant in line 702 of `ConsumptionManagement.ts`. This is due to the parsing function ignoring the possibility of `LRS` or other suffixes being including in the usage type, and only removing the word disk. The function needs to be rewritten to include this condition.

**Comment by ccasher** [comment]
LGTM!
