### ISSUE TITLE
Allow Azure Subscriptions to be pulled in chunks instead of all at once

### ISSUE THREAD

**Issue by 4upz** [cloud-carbon-footprint/cloud-carbon-footprint#1022]
## Context
Since we use the Azure Consumption Management API to get usage data, requests for estimates with a large Azure footprint may inevitably encounter rate limits that the API enforces. For these rate limits, we currently apply a retry logic that waits 30 seconds before trying to fetch data from the API again. Rate limit retries can be quite disruptive due to having to periodically wait 60 seconds during every request, and also over-populating the console output for each error encountered. We currently fetch data for all Azure subscriptions all at once, which further increases the chances of running into rate limit errors and needing to retry.

### Related Issue
- #906 
- #1021 

## Tasks

- [x] Implement config option to fetch Azure data in chunks by subscription. This includes an option to enable the chunk method and to specify the chunk size to their liking.
- [x] Implement config option to fetch Azure data synchronously, with the caveat that this will take the longest but will encounter less rate issues.
- [x] Implement config option to fetch Azure data by specific subscriptions/account by providing a list of desired subscriptions. Similar to chunks, but with higher specificity of what exact data to retrieve (instead of all data for the configured account)

## Tech Tasks
- [x] Add appropriate test coverage, including edge cases.
- [x] Run Changesets, bump any packages that have been updated/changed
- [x] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.
- [x] If any create-app templates have been updated, make sure to run the [test-create-app script](https://docs.google.com/document/d/1Ei6Cb2DjwEJUNtpULJSxbOuIdAfCARERgE3BSsKWrsc/edit) to ensure it still works properly.
