### ISSUE TITLE
[ANALYSIS SPIKE] Collecting anonymous data

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#194]
#### Overview
We have heard from a number of partners and folks in the climate tech space that there is desire for and value in creating metrics around sustainable tech, and in our case green cloud. The best way to begin thinking about what "good" looks like (which could be a powerful incentivizing tool) is to better understand the current landscape of different type of cloud users and what their setup and emissions look like. 
To learn this, we are exploring the possibility of an option for users to submit data anonymously.
This type of data analysis could also help us learn what practices and set ups work best for emissions reductions for different types of organizations.

This ticket is the beginning of our exploration and brainstorm of what might be possible, what we need to clarify or learn, and what further questions we need to ask.
This ticket focuses on logistics - technical, implementation, method of collection, initial legal concerns (may need to follow through again once we clarify the intended use of the data)
#### Out of Scope:
How we will use the data, features we may build for it, etc.
## Acceptance Criteria
- [ ] could we include this in guided-install, and double confirm
- [ ] small "survey" on org and use, etc?
- [ ] Check in with Jeremy
- [ ] Check in with Data Service Line
- [ ] Find any other examples
- [ ] All findings are documented in a google doc

## Questions to Ponder
- [ ] What carbon/usage data would we want to collect? (time period, values, summary vs underlying data, emissions/usage/cost)
- [ ] Can a submitter choose to give us only certain parts of their data? What options do they have and how?
- [ ] How would we collect org/submitter data?
- [ ] Are there any disqualifiers for submitting data?
- [ ] What function(s) would we use to collect the data? (CLI, survey, submit through microsite, etc.)
- [ ] What format would we collect the data in? (csv, spreadsheet, script to format data, etc.)
- [ ] Where would we store the data?
- [ ] How long would we hold on to the data? Does it expire? Does the submitter have input on this?
- [ ] How much data are we prepared to store (if many submitters from large orgs, could be a lot)?
- [ ] What to do if use of data changes (eg start analyzing a diff part or in a diff way; how do we inform submitters of the changed use)?
- [ ] Who owns the data - ThoughtWorks? Who has access and how do we control this?
- [ ] What combinations of information could make an org identifiable and how do we ensure complete anonymity?
- [ ] Do we have different levels of disclosure of information? Perhaps an org is fine with being identifiable 

## Tech Tasks
- [ ] Run Changesets, bump any packages that have been updated/changed
