### ISSUE TITLE
[WIP] Refactor frontend to better separate component concerns

### ISSUE THREAD

**Issue by 4upz-tw** [cloud-carbon-footprint/cloud-carbon-footprint#329]
**This Issue can be used as a template for each separate large component extraction/refactor issue we create.**

## Context
Currently, the frontend code of our app is organized in a way in which most components contain a single `.tsx` file with all of the component's logic, styles, and rendered HTML markup in one place. The file structure is also organized in a way in which most components sit at the root of the dashboard or other subfolder preventing the components and their related files grouped in the most intuitive way.

As we begin to design out a new potential dashboard for the recommendations feature and further expand the app's UI, we should refactor and organize our frontend in a way that follows a common React pattern of Container/Presentational components to improve the maintainability and readability of our code. This also includes extracting supporting logic from components such as js stylings into common or isolated files to be used as imports instead.

## Tasks
For each component we should do the following:
- [ ] Extract component's style hook into a separate `.ts` named after the component in camelcase _(`carbonIntensityStyles.ts`)_
- [ ] Extract the component's rendered HTML markup into a separate Presentational component `.tsx` file with the component's name _(i.e. `CarbonIntensityMap.tsx`)_ so that it can be rendered as one component by the container
- [ ] Convert any required data that the presentational component needs to props that are passed from the original component
- [ ] Rename the original component that now has all of the original logic and state as the component's name followed by the word container _(i.e. `CarbonIntensityMapContainer` or shorter)_
- [ ] Extract or create any necessary presentation-focused tests to a new file for the Presentational component
- [ ] Extract any necessary subcomponents

## Tech/Implementation Details
The following article is super helpful for understanding the Container/Presentational component pattern (also known as Smart/Dumb components!)
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)

Another good resource, mainly concerning the section for the structuring of a single component (the folder structure is way more than needed): https://betterprogramming.pub/how-you-should-structure-your-react-applications-e7dd32375a98

- Some components may be small and not even worth breaking into two components. In these cases, best judgement can be used to decide if the effort is worth it based on the possibility of that component being expanded in the future.
- There may be some repeated styles or reused components that may arise. These may need to be extracted or moved to a `common` subdirectory of that dashboard (such as the charts).

**Comment by 4upz-tw** [comment]
- Separate folder restructure into separate ticket
- Have container extractions or larger extractions be their own ticket
- Separate tickets for resolving duplications into common/reusable components and styles (can be subtask of extraction ticket)
