### ISSUE TITLE
Restructure frontend files into component-based folders

### ISSUE THREAD

**Issue by 4upz-tw** [cloud-carbon-footprint/cloud-carbon-footprint#335]
## Context
Currently, the frontend code of our app is organized in a way in which most components contain a single `.tsx` file with all of the component's logic, styles, and rendered HTML markup in one place. The file structure is also organized in a way in which most components sit at the root of the dashboard or other subfolder preventing the components and their related files from being grouped in the most intuitive way.

As we begin to design out a new potential dashboard for the recommendations feature and further expand the app's UI, we should refactor and organize our frontend in a way that groups a component and its related assets/subcomponents into a single folder for better navigation, organization of concerns, and maintainability. 

### Example: 

``` bash
CarbonIntensityMap
├── __snapshots__
│   └── CarbonIntensityMap.test.tsx.snap
├── AWSMap.svg
├── AzureMap.svg
├── CarbonIntensityMap.test.tsx
├── CarbonIntensityMap.tsx
├── GCPMap.svg
├── index.ts
└── carbonIntensityStyles.ts
```

## Tasks
For each primary dashboard component, do the following:
- [x] Create a subfolder in `/dashboard` with the component names in uppercase format _(i.e. `dashboard/CarbonIntensityMap`)_ to hold each of the component's files and supporting assets
- [x] Move the primary component into that subfolder, and update import paths as necessary (IntelliJ or VSCode should do this for you)
- [x] Create an `index.ts` file to export the component as the directory's default export (for easy imports)
- [x] Move test file of component into new subfolder
- [x] Identify any rendered subcomponents _(i.e. `ApexBarChart.ts`)_ and move them as well as their test files into the subfolder (make sure imports and paths are updated)
- [x] Check for any remaining assets (images, specific helper files, etc) and move them into the new folder as well

Afterwards:
- [x] Run Changesets, bump any packages that have been updated/changed
- [x] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.

## Tech/Implementation Details
This could also be a good opportunity to identify and organize any reused subcomponents into a common folder.

Good resource, especially for index exporting: https://medium.com/bootstart/you-should-be-using-folder-components-b30b7d165c39

- The CarbonIntensityMap was created with this directory pattern in mind, so it can be a good reference for how each component directory should look.

**Comment by 4upz-tw** [comment]
We may need to think about where to place non-dashboard specific components such as the InfoSidebar (previously named CarbonFormulaDrawer), HeaderBar, ErrorPage, and others. One idea that came up is a `src/common` folder for what will eventually be common components, styles, and other reusable files. Components that are used once but are relevant to the layout, such as HeaderBar and InfoSidebar (rendered only in App) could be in a subfolder called `src/common/layout`.

**Comment by 4upz-tw** [comment]
Today we focused on extracting non-dashboard specific files and commonly used components/helpers into appropriate subdirectories of the src folder (utils, layouts, and common). This cleans up the smaller subdirectories and loose files that were spread across the src and dashboard folders, with scalable thinking as far as what organization would work best as we plan to add new pages to the dashboard. 

Preview of new subdirectories under src: 

``` shell
layout
│   ├── ErrorPage
│   │   ├── ErrorPage.test.tsx
│   │   ├── ErrorPage.tsx
│   │   └── index.ts
│   ├── HeaderBar
│   │   ├── HeaderBar.tsx
│   │   └── index.ts
│   └── InfoSidebar
│       ├── InfoSidebar.test.tsx
│       ├── InfoSidebar.tsx
│       ├── __snapshots__
│       │   └── InfoSidebar.test.tsx.snap
│       └── index.ts
utils
    ├── data
    │   ├── data.json
    │   ├── generateEstimations.test.ts
    │   ├── generateEstimations.ts
    │   └── index.ts
    ├── helpers
    │   ├── index.ts
    │   ├── transformData.test.ts
    │   └── transformData.ts
    ├── hooks
    │   ├── EmissionFactorServiceHook.test.ts
    │   ├── EmissionFactorServiceHook.ts
    │   ├── RemoteServiceHook.test.ts
    │   ├── RemoteServiceHook.ts
    │   └── index.ts
    └── models
        └── types.ts
```

Next steps:

- Dive into `dashboard/filters` and `dashboard/charts` to ensure that those components are properly organized and exported, and which should be extracted.
- Give the `dashboard` folder a name that's representative of the page view it now holds. In addition, the `CarbonCloudContainer.tsx` should share the same name as well as be organized as the primary component/container for that page. (Some ideas that came up were _EmissionsMetricsPage_, _EmissionsPage_, and _EmissionsInsightsPage_)

**Comment by aalva05-tw** [comment]
Today we focused on extracting dashboard specific files and filters into appropriate subdirectories. We added a new `pages` directory under `src/pages` and moved the `EmissionssMetricPage`(previously named `dashboard`) and all its components to this new directory. This cleans up smaller subdirectories and sets the base for the new project structure as we plan to add new pages to the dashboard.

Preview of new subdirectories under src:

```
pages
└── EmissionsMetricsPag
│   ├──ApexDonutChart
│   ├──CarbonComparissonCard
│   ├──CarbonIntensityMap
│   ├──CloudUsage
│   ├──EmissionsBreakdownCard
│   └── FilterBar
│       └── Filters
│       │   └── AccountFilter.test.tsx
│       │   ├── AccountFilter.tsx
│       │   ├── CloudProviderFilter.tsx
│       │   ├── DateFilter.test.tsx
│       │   ├── DateFilter.tsx
│       │   ├── DropdownFilter.tsx
│       │   ├── MonthFilter.test.tsx
│       │   ├── MonthFilter.tsx
│       │   ├── ServiceFilter.test.tsx
│       │   ├── ServiceFilter.tsx
│       │   └── index.ts
│       └── utils
│           └──  DropdownConstants.test.ts
│           ├── DropdownConstants.ts
│           ├── FilterHook.test.ts
│           ├── FilterHook.ts
│           ├── Filters.test.ts
│           ├── Filters.ts
│           ├── FiltersUtil.test.ts
│           ├── FiltersUtil.ts
│           ├── __mocks__
│           │   └── Filters.ts
│           └── options
│               └──  AccountChooser.ts
│               ├── CloudProviderChooser.ts
│               ├── OptionChooser.ts
│               ├── ServiceChooser.ts
│               ├── common.ts
│               └── index.ts
├──EmissionsMetricsPage.test.tsx
├──EmissionsMetricsPage.tsx
└──index.ts
```

We haven't run the changeset or make any updates to the `create-app` templates as we wanted to have these new changes reviewed before we do this.

**Comment by dtoakley** [comment]
Looking great, I think I only have two questions / points of feedback:
1. `packages/client/src/pages/EmissionsMetricsPage/CloudUsage` -- I feel like this could be named `ApexLineChart` given that is what is contained in it. (the tooltip is only used in the line chart). 
2. I'm not sure the `models/types.ts` should exist in the `utils` directory, as it's not really utility classes/functions.... It's only not really models, so maybe just move the file inside `src` directory and call it `Types.ts` for now?

**Comment by 4upz-tw** [comment]
> Looking great, I think I only have two questions / points of feedback:
> 
> 1. `packages/client/src/pages/EmissionsMetricsPage/CloudUsage` -- I feel like this could be named `ApexLineChart` given that is what is contained in it. (the tooltip is only used in the line chart).
> 2. I'm not sure the `models/types.ts` should exist in the `utils` directory, as it's not really utility classes/functions.... It's only not really models, so maybe just move the file inside `src` directory and call it `Types.ts` for now?

Thanks for the feedback, Dan! In regards to your questions/comments: 

1. We named the folder 'CloudUsage' because there is some contained logic that we were gonna extract from the `EmissionsMetricsPage` that had the styling and wrapping container elements for the ApexLineChart. We were going to name that new container file CloudUsage and do the actual extraction as part of the work for a separate ticket that will focus on cleaning up that `EmissionsMetricsPage` component. However, if you don't think that's necessary, we can leave it and rename the folder!
2. You're probably right. The `models` subfolder already existed, so we just moved it in under `utils` and left it as a folder in case we ever decided to add a new types file for other pages/components. But I do agree, we can just leave it under `src` for now and cross that bridge if we ever get there.

**Comment by dtoakley** [comment]
I'm not 100% sure I follow the reasoning behind 1, but maybe could we rename the directory to `EmissionsOverTimeChart` or `EmissionsOverTimeCard` as that is what the Line Chart is all about. `CloudUsage` is just to vague/broad -- the whole front-end is about "Cloud Usage". Hope that makes sense.

**Comment by 4upz-tw** [comment]
That makes sense! I think we could definitely rename it to something better than `Cloud Usage` so we'll make that change
