### ISSUE TITLE
Frontend Refactor: CarbonComparisonCard

### ISSUE THREAD

**Issue by 4upz-tw** [cloud-carbon-footprint/cloud-carbon-footprint#343]
## Context
Refer to Issue #329 for the full context. This story will focus on refactoring the `CarbonComparisonCard.tsx` file to follow the presentational and container component pattern for better maintainability and separation of concerns. 

## Tasks
- [x] Extract component's style hook into a separate `.ts` named after the component in camelcase _(`carbonComparisonStyles.ts`)_
- [x] Extract the component's rendered HTML markup into a separate Presentational component `.tsx` file with the component's name _(i.e. `CarbonComparison.tsx`)_ so that it can be rendered as one component by the container 
- [x] Convert any required data that the presentational component needs to props that are passed from the original component
- [x] Extract any necessary subcomponents
- [x] Extract or create any new tests as necessary, especially for the presentational component

## Tech Tasks
- [x] Run Changesets, bump any packages that have been updated/changed
- [x] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.

## Tech/Implementation Details
The following article is super helpful for understanding the Container/Presentational component pattern (also known as Smart/Dumb components!)
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)

- Some components may be small and not even worth breaking into two components. In these cases, best judgement can be used to decide if the effort is worth it based on the possibility of that component being expanded in the future.
- There may be some repeated styles or reused components that may arise. These may need to be extracted or moved to the `src/common` directory.

**Comment by dtoakley** [comment]
This looks good -- particularly the introduction of the new `Source` and `ComparisonItem` types -- nice one.
