### ISSUE TITLE
Frontend Refactor: EmissionsBreakdownCard

### ISSUE THREAD

**Issue by 4upz-tw** [cloud-carbon-footprint/cloud-carbon-footprint#345]
## Context
Refer to Issue #329 for the full context. This story will focus on refactoring the `EmissionsBreakdownCard.tsx` file to follow the presentational and container component pattern for better maintainability and separation of concerns. 

## Tasks
- [x] Extract component's style hook into a separate `.ts` named after the component in camelcase _(`emissionsBreakdownCard.ts`)_
- [x] Extract the component's rendered HTML markup into a separate Presentational component `.tsx` file with the component's name _(i.e. `EmissionsBreakdownCard.tsx`)_ so that it can be rendered as one component by the container 
- [x] Convert any required data that the presentational component needs to props that are passed from the original component
- [x] Rename the original component that now has all of the original logic and state as the component's name followed by the word container _(i.e. `EmissionsBreakdownContainer` or shorter)_
- [x] Extract any necessary subcomponents
- [x] Extract or create any new tests as necessary, especially for the presentational component

## Tech Tasks
- [x] Run Changesets, bump any packages that have been updated/changed
- [x] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.

## Tech/Implementation Details
The following article is super helpful for understanding the Container/Presentational component pattern (also known as Smart/Dumb components!)
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)

- Some components may be small and not even worth breaking into two components. In these cases, best judgement can be used to decide if the effort is worth it based on the possibility of that component being expanded in the future.
- There may be some repeated styles or reused components that may arise. These may need to be extracted or moved to the `src/common` directory.

**Comment by 4upz-tw** [comment]
The EmissionsBreakdownContainer tests runs pretty slow. I think it's because the component is being rendered twice before each tests (once by the `create` function from `react-test-renderer` and another time by the `render` function of `react testing library`). I'm going to look into this and tweak the tests before doing additional refactoring.

**Comment by dtoakley** [comment]
This isn't a big deal and doesn't need to block this refactor, but I noticed some hardcoded colors like `backgroundColor: '#ababab',` in the `carbonIntensityRangeStyles.ts` file. 

Instead, we could either override one of the material UI theme's greys with something like:

```
grey: {
        A200: '#ABABAB',
      },
```
in `packages/client/src/utils/themes/index.ts` and reference them like `theme.palette.grey.A200`. Or we could no override it and just use the default `A200` grey because it's basically thre same as this custom grey. This will be more extensible and make the styles more manageable over time. Hard coded colors outside the theme are always a smell to me!

**Comment by 4upz-tw** [comment]
Thanks for the callout! I just pushed up changes that fixes the other hardcoded colors for this component and makes those grey references use Material's default grey instead. I'll make sure to keep an eye out for this issue during the remaining refactors!
