### ISSUE TITLE
Frontend Refactor: FilterBar

### ISSUE THREAD

**Issue by 4upz-tw** [cloud-carbon-footprint/cloud-carbon-footprint#346]
## Context
Refer to Issue #329 for the full context. This story will focus on refactoring the `FilterBard.tsx` file and supporting components to follow the presentational and container component pattern for better maintainability and separation of concerns. _This may follow and possibly overlap with the extraction that will happen from Issue #345 for EmissionsMetricsPage._ 

## Tasks
- [x] Extract component's style hook into a separate `.ts` named after the component in camelcase _(`filterBarStyles.ts`)_
- [x] Extract the component's rendered HTML markup into a separate Presentational component `.tsx` file with the component's name _(i.e. `FilterBar.tsx`)_ so that it can be rendered as one component by the container 
- [x] Convert any required data that the presentational component needs to props that are passed from the original component
- [x] Rename the original component that now has all of the original logic and state as the component's name followed by the word container _(i.e. `FilterBarContainer.ts` or shorter)_
  - Only if necessary since FilterBar will already serve as the container for all of the Filter subcomponents. 
- [x] Extract any necessary subcomponents
- [x] Extract or create any new tests as necessary, especially for the presentational component

## Tech Tasks
- [x] Run Changesets, bump any packages that have been updated/changed
- [x] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.

## Tech/Implementation Details
The following article is super helpful for understanding the Container/Presentational component pattern (also known as Smart/Dumb components!)
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)

- Some components may be small and not even worth breaking into two components. In these cases, best judgement can be used to decide if the effort is worth it based on the possibility of that component being expanded in the future.
- There may be some repeated styles or reused components that may arise. These may need to be extracted or moved to the `src/common` directory.

**Comment by 4upz-tw** [comment]
We should discuss if we wish to keep the ApexDonutChart or not
