### ISSUE TITLE
Add Search function to Microsite Docs

### ISSUE THREAD

**Issue by 4upz** [cloud-carbon-footprint/cloud-carbon-footprint#983]
## Context 
We currently use [Docusaurus](https://docusaurus.io) to power our Microsite, and it seems that they have [official support](https://docusaurus.io/docs/search) for Algolia  DocSearch as a search tool for documentation. Adding search to the CCF docs could provide tremendous value in helping to navigate the documentation and troubleshoot issues/setup. Fortunately, DocSearch is also free for open source projects 🥳 

_Note: This will be a task for CCF maintainers due to DocSearch application requires a project owner. _

## Tasks
- [x]  Double-check that we meet the criteria for the free DocSearch service, and apply to the program here 
- [x] Wait for approval from the DocSearch crawl program, and wait for results/snippet from Algolia (you can also verify crawl results in the [web interface]([the web interface](https://crawler.algolia.com/))
- [ ] Since we use the `@docusaurus/preset-classic` configuration, integration is easy since Algolia is natively supported. Follow the [official instructions](https://docusaurus.io/docs/search#connecting-algolia) to connect Algolia to the site

### Bonus
If you're feeling fancy, feel free to add a little CCF [style](https://docusaurus.io/docs/search#styling-your-algolia-search) to the search bar.
